-- 목적: 주간 지수 배치 결과(raw/tscore/persona) 저장 테이블 생성
-- 특이사항:
-- - snapshot_date + member_id 를 기본 키로 사용해 동일 날짜 중복 적재를 방지한다.
-- - persona 결과는 persona_type_id(FK) 기준으로 저장한다.

CREATE TABLE IF NOT EXISTS index_raw_snapshot (
    snapshot_date date NOT NULL,
    member_id bigint NOT NULL,
    explore_raw numeric NOT NULL,
    benefit_trend_raw numeric NOT NULL,
    multi_device_raw numeric NOT NULL,
    family_home_raw numeric NOT NULL,
    internet_security_raw numeric NOT NULL,
    stability_raw numeric NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_index_raw_snapshot PRIMARY KEY (snapshot_date, member_id)
);

CREATE INDEX IF NOT EXISTS idx_index_raw_snapshot_member
    ON index_raw_snapshot (member_id);

CREATE TABLE IF NOT EXISTS index_tscore_snapshot (
    snapshot_date date NOT NULL,
    member_id bigint NOT NULL,
    explore_tscore numeric NOT NULL,
    benefit_trend_tscore numeric NOT NULL,
    multi_device_tscore numeric NOT NULL,
    family_home_tscore numeric NOT NULL,
    internet_security_tscore numeric NOT NULL,
    stability_tscore numeric NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_index_tscore_snapshot PRIMARY KEY (snapshot_date, member_id)
);

CREATE INDEX IF NOT EXISTS idx_index_tscore_snapshot_member
    ON index_tscore_snapshot (member_id);

CREATE TABLE IF NOT EXISTS persona_type (
    persona_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_name VARCHAR(100) NOT NULL,
    short_desc TEXT,
    character_description TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_persona_type_name_version UNIQUE (character_name, version)
);

CREATE INDEX IF NOT EXISTS idx_persona_type_active_version
    ON persona_type (is_active, version DESC);

CREATE INDEX IF NOT EXISTS idx_persona_type_name
    ON persona_type (character_name);

CREATE TABLE IF NOT EXISTS index_persona_snapshot (
    snapshot_date date NOT NULL,
    member_id bigint NOT NULL,
    persona_type_id bigint NOT NULL,
    -- 하위 호환 및 운영 조회 편의를 위해 코드도 함께 저장한다.
    persona_code varchar(50) NOT NULL,
    source_index_code varchar(50) NOT NULL,
    source_tscore numeric NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_index_persona_snapshot PRIMARY KEY (snapshot_date, member_id),
    CONSTRAINT fk_index_persona_snapshot_member
        FOREIGN KEY (member_id) REFERENCES member (member_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_index_persona_snapshot_persona_type
        FOREIGN KEY (persona_type_id) REFERENCES persona_type (persona_type_id)
);

CREATE INDEX IF NOT EXISTS idx_index_persona_snapshot_member
    ON index_persona_snapshot (member_id);

CREATE INDEX IF NOT EXISTS idx_index_persona_snapshot_persona
    ON index_persona_snapshot (persona_code);

CREATE INDEX IF NOT EXISTS idx_index_persona_snapshot_persona_type_id
    ON index_persona_snapshot (persona_type_id);